stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - data/raw
  data_processing:
    cmd: python src/data_processing.py
    deps:
    - data/raw
    - src/data_processing.py
    outs:
    - data/processed
